[features]
seeds = false
skip-lint = false

[programs.devnet]
spl_token_minter = "HJhLRFu72TGNHUbeFoWhTPozP8EHQ4KJ3vqP7mPRD4n3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/shivamsoni/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

